### ISSUE TITLE
关于todo.3，眼睛应该看向哪里

### ISSUE THREAD

**Issue by 805033299** [zhenglw02/chat-jarvis#4]
## 眼睛看向电脑屏幕和现实世界理论上来说并不冲突。

1. 识别电脑屏幕内容可以*实时交互式*自动化的完成一些操作，包含但不仅限于excel编辑、ppt编辑、代码编写、视频剪辑等等，所有的电脑操作、软件使用，只要模型可以理解，完全可以干任何事情，但是就现在的能力来说，实现这样的功能还需要很长的时间。
2. 从对现实世界的识别来说，最主要的就是识别人的相关内容，行为、表情、着装等等，但是其实在使用电脑时，人的行为更多集中在眼睛和手，识别这些似乎无法获取很多有用的信息。

以目前模型的能力，这样的交互式识别以及操作可能只能实现简单的一些电脑操作，对于一个正常使用者来说相当鸡肋。但是，换一个角度，对于原本无法使用电脑的人这样的功能简直是变革，可以识别声音、手势，对于盲人、残疾人等来说，这无异于打开新世界的大门。在实现这些简单操作的基础上，随着模型能力的发展，可以逐步拥有更多的功能，最终实现交互式的电脑操作，这将是一个很强大产品。

**Comment by zhenglw02** [comment]
非常感谢您的建议，关于这两点我之前也有做过调研。
看向电脑屏幕，并操作电脑软件的方式，产业界已有一些demo产品，比如实在智能的TARS，能识别并操作常见的各种软件，比如office系列软件和主流即时通讯软件等，TARS已经比较符合我对看向电脑屏幕的智能管家的想象了。
我目前比较倾向于让贾维斯看向现实世界，贾维斯以后可能不局限于在电脑上运行，可能会在类机器人硬件中运行，让贾维斯真正进入现实世界。在实现上，主流的AI能力开放平台都提供了图像标签识别、人体识别、手势识别等，我计划组合这些能力，为贾维斯的大脑提供现实世界的信息。
不管怎么说，为贾维斯加上眼睛都是个艰巨的任务，我会尽量努力让最终效果达到预期。

**Comment by zhenglw02** [comment]
眼睛组件第一版已开发完成，看向的是屏幕外面。欢迎大家继续给贾维斯提建议。
